name: Deploy to GCP Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # 기본 환경은 우분투로 두고, 도커 이미지를 실행하도록 설정

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCP credentials
      uses: google-github-actions/auth@v0.5.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up kubectl
      uses: google-github-actions/setup-kubectl@v2
      with:
        kubeconfig: ${{ secrets.GCP_SA_KEY }}

    - name: Run custom Docker image with kubectl
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace -e KUBECONFIG=$HOME/.kube/config thdrudtjssla/brick-blockgame:latest kubectl apply -f k8s-deployment.yaml
        docker run --rm -v $(pwd):/workspace -w /workspace -e KUBECONFIG=$HOME/.kube/config thdrudtjssla/brick-blockgame:latest kubectl apply -f k8s-service.yaml

