me: Deploy to GCP Kubernetes

on:
    push:
          branches:
                  - main

          jobs:
              deploy:
                    runs-on: ubuntu-latest
                          steps:
                                - name: Checkout code
                                        uses: actions/checkout@v2

                                              - name: Set up GCP credentials
                                                      uses: google-github-actions/auth@v0.5.0
                                                              with:
                                                                        credentials_json: ${{ secrets.GCP_SA_KEY }}

                                                                              - name: Set up kubectl
                                                                                      uses: google-github-actions/setup-kubectl@v0.2.0
                                                                                              with:
                                                                                                        kubeconfig: ${{ secrets.GCP_SA_KEY }}

                                                                                                              - name: Deploy to Kubernetes
                                                                                                                      run: |
                                                                                                                                kubectl apply -f k8s-deployment.yaml
                                                                                                                                        kubectl apply -f k8s-service.yaml

